apiVersion: v1
kind: Namespace
metadata:
  name: demo-kyverno-vpa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: demo-kyverno-vpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: nginx:latest
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi 