apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: disallow-privileged-containers-policy
spec:
  steps:
  - name: step-01
    try:
    - apply:
        file: ../disallow-privileged-containers.yaml
    - patch:
        resource:
          apiVersion: kyverno.io/v1
          kind: ClusterPolicy
          metadata:
            name: disallow-privileged-containers
          spec:
            validationFailureAction: Enforce
    - assert:
        file: policy-assert.yaml
  - name: step-02
    try:
    - apply:
        file: good-resource.yaml
    - apply:
        expect:
        - check:
            ($error != null): true
        file: bad-resource.yaml
