apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-resources
spec:
  background: true
  rules:
  - name: cpu
    match:
      any:
      - resources:
          kinds:
          - Deployment
          - StatefulSet
    validate:
      message: "CPU request is not within VPA recommendations"
      pattern:
        spec:
          template:
            spec:
              containers:
              - name: "*"
                resources:
                  requests:
                    cpu: "{{vpa.recommendation.containerRecommendations[0].target.cpu}}"
  - name: memory
    match:
      any:
      - resources:
          kinds:
          - Deployment
          - StatefulSet
    validate:
      message: "Memory request is not within VPA recommendations"
      pattern:
        spec:
          template:
            spec:
              containers:
              - name: "*"
                resources:
                  requests:
                    memory: "{{vpa.recommendation.containerRecommendations[0].target.memory}}" 