apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-labels
spec:
  validationFailureAction: Audit
status:
  conditions: [
    {
      "message": "Ready",
      "status": "True",
    }
  ]
