apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpa-recommender
  namespace: vpa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-recommender
  namespace: vpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpa-recommender
  template:
    metadata:
      labels:
        app: vpa-recommender
    spec:
      serviceAccountName: vpa-recommender
      containers:
      - name: recommender
        image: registry.k8s.io/autoscaling/vpa-recommender:0.14.0
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 50m
            memory: 500Mi
        ports:
        - name: prometheus
          containerPort: 8942
        command:
        - ./recommender
        - --v=4
        - --stderrthreshold=info
        - --pod-recommendation-min-cpu-millicores=5
        - --pod-recommendation-min-memory-mb=50
        - --kube-api-qps=100
        - --kube-api-burst=200
        - --metrics-address=:8942
        - --storage=prometheus
        - --prometheus-address=http://prometheus-server.prometheus.svc.cluster.local:80 